{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-camera2",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-camera2-1.3.1.aar",
          "url": "camera-camera2-1.3.1.aar",
          "size": 448624,
          "sha512": "4955b742ae728d60130824c98a2c64a0e5b11b5de9f579a67b6cb0865e63fdb0bc784fb1fca07e0d17b5e55a758f63e1e7061b07c28202bb865fd4e8c1cc5307",
          "sha256": "e0e40ae66faea9a812c82eb865c95714f2e4f7c84ad7f7d7a92f00422cbe5f7d",
          "sha1": "5cf5355efeaadc3adc729fb0dea232f7e3db683c",
          "md5": "387a6af99e7805832f21eadf13ea9a9c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-camera2-1.3.1.aar",
          "url": "camera-camera2-1.3.1.aar",
          "size": 448624,
          "sha512": "4955b742ae728d60130824c98a2c64a0e5b11b5de9f579a67b6cb0865e63fdb0bc784fb1fca07e0d17b5e55a758f63e1e7061b07c28202bb865fd4e8c1cc5307",
          "sha256": "e0e40ae66faea9a812c82eb865c95714f2e4f7c84ad7f7d7a92f00422cbe5f7d",
          "sha1": "5cf5355efeaadc3adc729fb0dea232f7e3db683c",
          "md5": "387a6af99e7805832f21eadf13ea9a9c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-camera2-1.3.1-sources.jar",
          "url": "camera-camera2-1.3.1-sources.jar",
          "size": 351824,
          "sha512": "af0d61c405721f582b9b59274033f117cb732b4e2e75f27da89844857155ead40a7562ed7979453cda4d726ed7f51643c497f6779b1175030b5ecac1446255c4",
          "sha256": "3f338fa35a56656b2b4d6f376c3e605b0e32885244d87d2e7b05a4b283bd1741",
          "sha1": "bdd66645a838a7a280a4c0221cd5f59f12ef6d0b",
          "md5": "59b6a75ccf1325655b158151fa17d729"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-camera2-1.3.1-versionMetadata.json",
          "url": "camera-camera2-1.3.1-versionMetadata.json",
          "size": 3277,
          "sha512": "3457aaf1daae3c23df1afa125444b2c9febccd6c8eee62fddb37b74e4d217ea8183aafd55fe757191cd7be2d45e078616d54dbb1f172558a02fe063cbec75f1f",
          "sha256": "d8cec82581880afa10cba43907db64357c3f6a765fd7598a042eb7943b1019f4",
          "sha1": "f1e5deb7118484ad497eec922b64b108f5993b67",
          "md5": "6d6e3a9187e23ee6c4cd6dfcaa04b2b9"
        }
      ]
    }
  ]
}