{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-extensions",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-extensions-1.3.1.aar",
          "url": "camera-extensions-1.3.1.aar",
          "size": 120940,
          "sha512": "ce461e9dd4fccfa0e5d91f60b519d4b9efee41f78c30d557d8e7c39efa2b3c1184fb2596046d0080da81919a41de6bb408dcf2dc3a5fd01cb74170211f725834",
          "sha256": "d2b4c51f35f75801ea842f2d13e166852dc349fdd7861fb5bda058b187a5e1d1",
          "sha1": "8e7ce3cb1d0835f3fbe4721925b4bb6fc6f5b9a5",
          "md5": "3102d459106f417cade6fac44773d337"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-extensions-1.3.1.aar",
          "url": "camera-extensions-1.3.1.aar",
          "size": 120940,
          "sha512": "ce461e9dd4fccfa0e5d91f60b519d4b9efee41f78c30d557d8e7c39efa2b3c1184fb2596046d0080da81919a41de6bb408dcf2dc3a5fd01cb74170211f725834",
          "sha256": "d2b4c51f35f75801ea842f2d13e166852dc349fdd7861fb5bda058b187a5e1d1",
          "sha1": "8e7ce3cb1d0835f3fbe4721925b4bb6fc6f5b9a5",
          "md5": "3102d459106f417cade6fac44773d337"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-extensions-1.3.1-sources.jar",
          "url": "camera-extensions-1.3.1-sources.jar",
          "size": 86767,
          "sha512": "f5ad12498a96a80fb6be71e752d98d4f32f6af91e278ea003f322886103db7fc4e46873a56edaebb6cfb86f25be2819cd5e238fc7a2f855d8e3534402f171c15",
          "sha256": "075faf1f72cd28c7c49a00b6da804ce0063a2fe43c4b1fa3c8a3f6d5f83971b3",
          "sha1": "7f77249e42fa007228d6a127809ae0bf8ae474b5",
          "md5": "81939006011f61c1fa2008a85a5c7b33"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.1"
          },
          "reason": "camera-extensions is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-extensions-1.3.1-versionMetadata.json",
          "url": "camera-extensions-1.3.1-versionMetadata.json",
          "size": 923,
          "sha512": "0de85320461fdbd5b6c70418aab7bd0968b911dde69606c5be8440dfadbc8b84e1ce8df35f1dff4f87f21e64de6d85bb64514aab6d35a6b1ab1d3b99243189cb",
          "sha256": "0f83580697607609d02aa20e97946c62a29b9f10e9f9b70b33b49528db564f11",
          "sha1": "b22652fd98e552b7b8de748fb59a642a67b25f94",
          "md5": "6c61512f6a074f1be1b4fb3d5eb34b38"
        }
      ]
    }
  ]
}